#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/wallpapers-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3010
      - APP_ACCESS_TOKEN=${APP_ACCESS_TOKEN}
      - IMMICH_ALBUM_ID=${IMMICH_ALBUM_ID}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
      - IMMICH_BASE_URL=${IMMICH_BASE_URL}
    ports:
      - "3010:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
