#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/wallpapers-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3010
    ports:
      - "3010:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
